// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartAndSmaterAPI.Models;

#nullable disable

namespace SmartAndSmaterAPI.Migrations
{
    [DbContext(typeof(SASDbContext))]
    [Migration("20230307172524_AddedWeaponType")]
    partial class AddedWeaponType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartAndSmaterAPI.Models.Armor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BarbarianCanUse")
                        .HasColumnType("bit");

                    b.Property<float?>("BlackArmorMax")
                        .IsRequired()
                        .HasColumnType("real");

                    b.Property<float>("BlackArmorMin")
                        .HasColumnType("real");

                    b.Property<float>("BlueArmorMax")
                        .HasColumnType("real");

                    b.Property<float>("BlueArmorMin")
                        .HasColumnType("real");

                    b.Property<bool>("ClericCanUse")
                        .HasColumnType("bit");

                    b.Property<bool>("FighterCanUse")
                        .HasColumnType("bit");

                    b.Property<float>("GoldArmorMax")
                        .HasColumnType("real");

                    b.Property<float>("GoldArmorMin")
                        .HasColumnType("real");

                    b.Property<float>("GreenArmorMax")
                        .HasColumnType("real");

                    b.Property<float>("GreenArmorMin")
                        .HasColumnType("real");

                    b.Property<float>("GreyArmorMax")
                        .HasColumnType("real");

                    b.Property<float>("GreyArmorMin")
                        .HasColumnType("real");

                    b.Property<string>("ImageLocation")
                        .IsRequired()
                        .HasColumnType("varchar(1024)");

                    b.Property<float>("MovementSpeed")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<float>("OrangeArmorMax")
                        .HasColumnType("real");

                    b.Property<float>("OrangeArmorMin")
                        .HasColumnType("real");

                    b.Property<float>("PurpleArmorMax")
                        .HasColumnType("real");

                    b.Property<float>("PurpleArmorMin")
                        .HasColumnType("real");

                    b.Property<bool>("RangerCanUse")
                        .HasColumnType("bit");

                    b.Property<bool>("RogueCanUse")
                        .HasColumnType("bit");

                    b.Property<string>("Stats")
                        .HasColumnType("varchar(1024)");

                    b.Property<float>("WhiteArmorMax")
                        .HasColumnType("real");

                    b.Property<float>("WhiteArmorMin")
                        .HasColumnType("real");

                    b.Property<bool>("WizardCanUse")
                        .HasColumnType("bit");

                    b.Property<int>("armorType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Armors");
                });

            modelBuilder.Entity("SmartAndSmaterAPI.Models.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionMovementSpeed")
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("BarbarianCanUse")
                        .HasColumnType("bit");

                    b.Property<float?>("BlackDamageMax")
                        .IsRequired()
                        .HasColumnType("real");

                    b.Property<float>("BlackDamageMin")
                        .HasColumnType("real");

                    b.Property<float>("BlueDamageMax")
                        .HasColumnType("real");

                    b.Property<float>("BlueDamageMin")
                        .HasColumnType("real");

                    b.Property<bool>("ClericCanUse")
                        .HasColumnType("bit");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FighterCanUse")
                        .HasColumnType("bit");

                    b.Property<float>("GoldDamageMax")
                        .HasColumnType("real");

                    b.Property<float>("GoldDamageMin")
                        .HasColumnType("real");

                    b.Property<float>("GreenDamageMax")
                        .HasColumnType("real");

                    b.Property<float>("GreenDamageMin")
                        .HasColumnType("real");

                    b.Property<float>("GreyDamageMax")
                        .HasColumnType("real");

                    b.Property<float>("GreyDamageMin")
                        .HasColumnType("real");

                    b.Property<string>("Hand")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ImageLocation")
                        .IsRequired()
                        .HasColumnType("varchar(1024)");

                    b.Property<float>("MovementSpeedWhileEquiped")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<float>("OrangeDamageMax")
                        .HasColumnType("real");

                    b.Property<float>("OrangeDamageMin")
                        .HasColumnType("real");

                    b.Property<float>("PurpleDamageMax")
                        .HasColumnType("real");

                    b.Property<float>("PurpleDamageMin")
                        .HasColumnType("real");

                    b.Property<bool>("RangerCanUse")
                        .HasColumnType("bit");

                    b.Property<bool>("RogueCanUse")
                        .HasColumnType("bit");

                    b.Property<string>("UniqueLink")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("UniqueName")
                        .HasColumnType("varchar(64)");

                    b.Property<int>("WeaponType")
                        .HasColumnType("int");

                    b.Property<float>("WhiteDamageMax")
                        .HasColumnType("real");

                    b.Property<float>("WhiteDamageMin")
                        .HasColumnType("real");

                    b.Property<bool>("WizardCanUse")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Weapons");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Weapon");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SmartAndSmaterAPI.Models.Bow", b =>
                {
                    b.HasBaseType("SmartAndSmaterAPI.Models.Weapon");

                    b.Property<float>("Attack1Speed")
                        .HasColumnType("real");

                    b.Property<int>("QuiverSize")
                        .HasColumnType("int");

                    b.Property<float>("ReloadSpeed")
                        .HasColumnType("real");

                    b.ToTable("Weapons", t =>
                        {
                            t.Property("Attack1Speed")
                                .HasColumnName("Bow_Attack1Speed");
                        });

                    b.HasDiscriminator().HasValue("Bow");
                });

            modelBuilder.Entity("SmartAndSmaterAPI.Models.MagicWeapon", b =>
                {
                    b.HasBaseType("SmartAndSmaterAPI.Models.Weapon");

                    b.Property<float?>("Attack1DamageMultiplier")
                        .HasColumnType("real");

                    b.Property<float?>("Attack1Speed")
                        .HasColumnType("real");

                    b.Property<string>("Attack1Type")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<float?>("Attack2DamageMultiplier")
                        .HasColumnType("real");

                    b.Property<float?>("Attack2Speed")
                        .HasColumnType("real");

                    b.Property<string>("Attack2Type")
                        .HasColumnType("varchar(32)");

                    b.Property<float?>("Attack3DamageMultiplier")
                        .HasColumnType("real");

                    b.Property<float?>("Attack3Speed")
                        .HasColumnType("real");

                    b.Property<string>("Attack3Type")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Reach")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SweetSpot")
                        .HasColumnType("varchar(64)");

                    b.ToTable("Weapons", t =>
                        {
                            t.Property("Attack1DamageMultiplier")
                                .HasColumnName("MagicWeapon_Attack1DamageMultiplier");

                            t.Property("Attack1Speed")
                                .HasColumnName("MagicWeapon_Attack1Speed");

                            t.Property("Attack1Type")
                                .HasColumnName("MagicWeapon_Attack1Type");

                            t.Property("Attack2DamageMultiplier")
                                .HasColumnName("MagicWeapon_Attack2DamageMultiplier");

                            t.Property("Attack2Speed")
                                .HasColumnName("MagicWeapon_Attack2Speed");

                            t.Property("Attack2Type")
                                .HasColumnName("MagicWeapon_Attack2Type");

                            t.Property("Attack3DamageMultiplier")
                                .HasColumnName("MagicWeapon_Attack3DamageMultiplier");

                            t.Property("Attack3Speed")
                                .HasColumnName("MagicWeapon_Attack3Speed");

                            t.Property("Attack3Type")
                                .HasColumnName("MagicWeapon_Attack3Type");

                            t.Property("Reach")
                                .HasColumnName("MagicWeapon_Reach");

                            t.Property("SweetSpot")
                                .HasColumnName("MagicWeapon_SweetSpot");
                        });

                    b.HasDiscriminator().HasValue("MagicWeapon");
                });

            modelBuilder.Entity("SmartAndSmaterAPI.Models.MeleeWeapon", b =>
                {
                    b.HasBaseType("SmartAndSmaterAPI.Models.Weapon");

                    b.Property<float>("Attack1DamageMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("Attack1Speed")
                        .HasColumnType("real");

                    b.Property<string>("Attack1Type")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<float?>("Attack2DamageMultiplier")
                        .HasColumnType("real");

                    b.Property<float?>("Attack2Speed")
                        .HasColumnType("real");

                    b.Property<string>("Attack2Type")
                        .HasColumnType("varchar(32)");

                    b.Property<float?>("Attack3DamageMultiplier")
                        .HasColumnType("real");

                    b.Property<float?>("Attack3Speed")
                        .HasColumnType("real");

                    b.Property<string>("Attack3Type")
                        .HasColumnType("varchar(32)");

                    b.Property<float?>("Attack4DamageMultiplier")
                        .HasColumnType("real");

                    b.Property<float?>("Attack4Speed")
                        .HasColumnType("real");

                    b.Property<string>("Attack4Type")
                        .HasColumnType("varchar(32)");

                    b.Property<float?>("Attack5DamageMultiplier")
                        .HasColumnType("real");

                    b.Property<float?>("Attack5Speed")
                        .HasColumnType("real");

                    b.Property<string>("Attack5Type")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Reach")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SweetSpot")
                        .HasColumnType("varchar(64)");

                    b.ToTable("Weapons", t =>
                        {
                            t.Property("Reach")
                                .HasColumnName("MeleeWeapon_Reach");
                        });

                    b.HasDiscriminator().HasValue("MeleeWeapon");
                });

            modelBuilder.Entity("SmartAndSmaterAPI.Models.Sheild", b =>
                {
                    b.HasBaseType("SmartAndSmaterAPI.Models.Weapon");

                    b.Property<string>("Reach")
                        .HasColumnType("varchar(64)");

                    b.HasDiscriminator().HasValue("Sheild");
                });
#pragma warning restore 612, 618
        }
    }
}
